name: Build and Deploy to EC2

on:
  push:
    branches: [ "develop"]

env:
  AWS_REGION: ap-northeast-2
  AWS_CODE_DEPLOY_APPLICATION: haru-app-deploy
  AWS_CODE_DEPLOY_GROUP: haru-app-deploy-group

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.CICD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CICD_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Build with jib
        run: |
          ./gradlew jib \
          -Djib.to.image="${{ secrets.DOCKERHUB_REPOSITORY }}/haru/develop:1.0.0"