name: Build and Deploy to EC2

on:
  push:
    branches: [ "develop"]

env:
  AWS_REGION: ap-northeast-2
  AWS_CODE_DEPLOY_APPLICATION: haru-app-deploy
  AWS_CODE_DEPLOY_GROUP: haru-app-deploy-group

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set environment variables
        run: |
          echo "::set-env name=ACCESS_KEY::${{ secrets.CICD_ACCESS_KEY }}"
          echo "::set-env name=SECRET_KEY::${{ secrets.CICD_SECRET_KEY }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}